[package]
name = "extism_cancel"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
querymt = { path = "../../../querymt" }
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
env_logger = "0.11"
log = "0.4"
